const characters: Array<string>[] = [
  ["여행자 바람", "Traveler_anemo", "바람", "한손검", "5"],
  ["여행자 바위", "Traveler_geo", "바위", "한손검", "5"],
  ["여행자 번개", "Traveler_electro", "번개", "한손검", "5"],
  ["여행자 풀", "Traveler_dendro", "풀", "한손검", "5"],
  ["다이루크", "Diluc", "불", "양손검", "5"],
  ["진", "Jean", "바람", "한손검", "5"],
  ["모나", "Mona", "물", "법구", "5"],
  ["치치", "Qiqi", "얼음", "한손검", "5"],
  ["벤티", "Venti", "바람", "활", "5"],
  ["클레", "Klee", "불", "법구", "5"],
  ["타르탈리아", "Tartaglia", "물", "활", "5"],
  ["종려", "Zhongli", "바위", "장병기", "5"],
  ["알베도", "Albedo", "바위", "한손검", "5"],
  ["감우", "Ganyu", "얼음", "활", "5"],
  ["소", "Xiao", "바람", "장병기", "5"],
  ["각청", "Keqing", "번개", "한손검", "5"],
  ["호두", "Hutao", "불", "장병기", "5"],
  ["유라", "Eula", "얼음", "양손검", "5"],
  ["카에데하라 카즈하", "Kaedehara Kazuha", "바람", "한손검", "5"],
  ["카미사토 아야카", "Kamisato Ayaka", "얼음", "한손검", "5"],
  ["요이미야", "Yoimiya", "불", "활", "5"],
  ["라이덴 쇼군", "Raiden Shougun", "번개", "장병기", "5"],
  ["산고노미야 코코미", "Sangonomiya Kokomi", "물", "법구", "5"],
  ["에일로이", "Aloy", "얼음", "활", "5"],
  ["아라타키 이토", "Arataki Itto", "바위", "양손검", "5"],
  ["신학", "Shenhe", "얼음", "장병기", "5"],
  ["야에 미코", "Yae Miko", "번개", "법구", "5"],
  ["카미사토 아야토", "Kamisato Ayato", "물", "한손검", "5"],
  ["야란", "Yelan", "물", "활", "5"],
  ["타이나리", "Tighnari", "풀", "활", "5"],
  ["사이노", "Cyno", "번개", "장병기", "5"],
  ["닐루", "Nilou", "물", "한손검", "5"],
  ["나히다", "Nahida", "풀", "법구", "5"],
  ["방랑자", "Wanderer", "바람", "법구", "5"],

  ["케이야", "Kaeya", "얼음", "한손검", "4"],
  ["리사", "Lisa", "번개", "법구", "4"],
  ["앰버", "Amber", "불", "활", "4"],
  ["피슬", "Fischl", "번개", "활", "4"],
  ["바바라", "Barbara", "물", "법구", "4"],
  ["향릉", "Xiangling", "불", "장병기", "4"],
  ["노엘", "Noelle", "바위", "양손검", "4"],
  ["설탕", "Sucrose", "바람", "법구", "4"],
  ["행추", "Xingqiu", "물", "한손검", "4"],
  ["북두", "Beidou", "번개", "양손검", "4"],
  ["응추", "Ningguang", "바위", "법구", "4"],
  ["디오나", "Diona", "얼음", "활", "4"],
  ["신염", "Xinyan", "불", "양손검", "4"],
  ["중운", "Chongyun", "얼음", "양손검", "4"],
  ["레이저", "Razor", "번개", "양손검", "4"],
  ["베넷", "Bennett", "불", "한손검", "4"],
  ["로자리아", "Rosaria", "얼음", "장병기", "4"],
  ["연비", "Yanfei", "불", "법구", "4"],
  ["사유", "Sayu", "바람", "양손검", "4"],
  ["쿠죠 사라", "Kujou Sara", "번개", "활", "4"],
  ["토마", "Thoma", "불", "장병기", "4"],
  ["고로", "Gorou", "바위", "활", "4"],
  ["운근", "Yunjin", "바위", "장병기", "4"],
  ["쿠키 시노부", "Kuki Shinobu", "번개", "한손검", "4"],
  ["시카노인 헤이조", "Shikanoin Heizou", "바람", "법구", "4"],
  ["콜레이", "Collei", "풀", "활", "4"],
  ["도리", "Dori", "번개", "양손검", "4"],
  ["캔디스", "Candace", "물", "장병기", "4"],
  ["레일라", "Layla", "얼음", "한손검", "4"],
  ["파루잔", "Faruzan", "바람", "활", "4"],
];

const combinations: Array<Array<string>> = [
  ["Hutao", "Xingqiu", "Zhongli", "Bennett"],
  ["Hutao", "Xingqiu", "Zhongli", "Qiqi"],
  ["Hutao", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Hutao", "Xingqiu", "Sucrose", "Bennett"],
  ["Hutao", "Xingqiu", "Albedo", "Bennett"],
  ["Hutao", "Xingqiu", "Raiden Shougun", "Bennett"],
  ["Hutao", "Xingqiu", "Yae Miko", "Bennett"],
  ["Hutao", "Xingqiu", "Fischl", "Bennett"],
  ["Hutao", "Mona", "Zhongli", "Bennett"],
  ["Hutao", "Mona", "Zhongli", "Qiqi"],
  ["Hutao", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Hutao", "Mona", "Sucrose", "Bennett"],
  ["Hutao", "Mona", "Albedo", "Bennett"],
  ["Hutao", "Mona", "Raiden Shougun", "Bennett"],
  ["Hutao", "Mona", "Yae Miko", "Bennett"],
  ["Hutao", "Mona", "Fischl", "Bennett"],

  ["Keqing", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Keqing", "Xingqiu", "Kaedehara Kazuha", "Jean"],
  ["Keqing", "Xingqiu", "Zhongli", "Bennett"],
  ["Keqing", "Xingqiu", "Zhongli", "Jean"],
  ["Keqing", "Xingqiu", "Raiden Shougun", "Bennett"],
  ["Keqing", "Xingqiu", "Raiden Shougun", "Jean"],
  ["Keqing", "Xingqiu", "Venti", "Bennett"],
  ["Keqing", "Xingqiu", "Venti", "Jean"],
  ["Keqing", "Xingqiu", "Sucrose", "Bennett"],
  ["Keqing", "Xingqiu", "Sucrose", "Jean"],
  ["Keqing", "Xingqiu", "Yae Miko", "Bennett"],
  ["Keqing", "Xingqiu", "Yunjin", "Bennett"],
  ["Keqing", "Mona", "Kaedehara Kazuha", "Zhongli"],
  ["Keqing", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Keqing", "Mona", "Kaedehara Kazuha", "Jean"],
  ["Keqing", "Mona", "Venti", "Bennett"],
  ["Keqing", "Mona", "Venti", "Jean"],
  ["Keqing", "Raiden Shougun", "Yae Miko", "Bennett"],
  ["Keqing", "Raiden Shougun", "Kujou Sara", "Bennett"],
  ["Keqing", "Raiden Shougun", "Yae Miko", "Sangonomiya Kokomi"],
  ["Keqing", "Raiden Shougun", "Kujou Sara", "Sangonomiya Kokomi"],
  ["Keqing", "Raiden Shougun", "Nahida", "Sangonomiya Kokomi"],
  ["Keqing", "Raiden Shougun", "Nahida", "Zhongli"],
  ["Keqing", "Raiden Shougun", "Nahida", "Layla"],
  ["Keqing", "Raiden Shougun", "Nahida", "Diona"],
  ["Keqing", "Yae Miko", "Nahida", "Zhongli"],
  ["Keqing", "Yae Miko", "Nahida", "Layla"],
  ["Keqing", "Yae Miko", "Nahida", "Diona"],
  ["Keqing", "Fischl", "Nahida", "Zhongli"],
  ["Keqing", "Fischl", "Nahida", "Layla"],
  ["Keqing", "Fischl", "Nahida", "Diona"],
  ["Keqing", "Nahida", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Keqing", "Nahida", "Venti", "Kuki Shinobu"],
  ["Keqing", "Nahida", "Sucrose", "Kuki Shinobu"],
  ["Keqing", "Nahida", "Kaedehara Kazuha", "Dori"],
  ["Keqing", "Nahida", "Venti", "Dori"],
  ["Keqing", "Nahida", "Sucrose", "Dori"],

  ["Ganyu", "Mona", "Venti", "Diona"],
  ["Ganyu", "Mona", "Kaedehara Kazuha", "Diona"],
  ["Ganyu", "Mona", "Sucrose", "Diona"],
  ["Ganyu", "Shenhe", "Venti", "Bennett"],
  ["Ganyu", "Shenhe", "Kaedehara Kazuha", "Bennett"],
  ["Ganyu", "Shenhe", "Sucrose", "Bennett"],
  ["Ganyu", "Shenhe", "Venti", "Sangonomiya Kokomi"],
  ["Ganyu", "Shenhe", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Ganyu", "Shenhe", "Sucrose", "Sangonomiya Kokomi"],
  ["Ganyu", "Shenhe", "Bennett", "Sangonomiya Kokomi"],
  ["Ganyu", "Xiangling", "Zhongli", "Bennett"],
  ["Ganyu", "Nahida", "Zhongli", "Bennett"],
  ["Ganyu", "Nahida", "Kaedehara Kazuha", "Bennett"],
  ["Ganyu", "Nahida", "Venti", "Bennett"],

  ["Diluc", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Diluc", "Xingqiu", "Venti", "Bennett"],
  ["Diluc", "Xingqiu", "Sucrose", "Bennett"],
  ["Diluc", "Xingqiu", "Zhongli", "Bennett"],
  ["Diluc", "Xingqiu", "Raiden Shougun", "Bennett"],
  ["Diluc", "Xingqiu", "Yae Miko", "Bennett"],
  ["Diluc", "Xingqiu", "Fischl", "Bennett"],
  ["Diluc", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Diluc", "Mona", "Venti", "Bennett"],
  ["Diluc", "Mona", "Sucrose", "Bennett"],
  ["Diluc", "Mona", "Zhongli", "Bennett"],
  ["Diluc", "Mona", "Raiden Shougun", "Bennett"],
  ["Diluc", "Mona", "Yae Miko", "Bennett"],
  ["Diluc", "Mona", "Fischl", "Bennett"],
  ["Diluc", "Sangonomiya Kokomi", "Kaedehara Kazuha", "Bennett"],
  ["Diluc", "Sangonomiya Kokomi", "Venti", "Bennett"],
  ["Diluc", "Sangonomiya Kokomi", "Zhongli", "Bennett"],
  ["Diluc", "Sangonomiya Kokomi", "Sucrose", "Bennett"],
  ["Diluc", "Chongyun", "Sucrose", "Bennett"],

  ["Raiden Shougun", "Zhongli", "Kaedehara Kazuha", "Bennett"],
  ["Raiden Shougun", "Zhongli", "Venti", "Bennett"],
  ["Raiden Shougun", "Zhongli", "Sucrose", "Bennett"],
  ["Raiden Shougun", "Zhongli", "Xiangling", "Bennett"],
  ["Raiden Shougun", "Yae Miko", "Xiangling", "Bennett"],
  ["Raiden Shougun", "Yae Miko", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Raiden Shougun", "Kujou Sara", "Kaedehara Kazuha", "Bennett"],
  ["Raiden Shougun", "Kujou Sara", "Zhongli", "Bennett"],
  ["Raiden Shougun", "Kujou Sara", "Yae Miko", "Bennett"],
  ["Raiden Shougun", "Kujou Sara", "Yae Miko", "Sangonomiya Kokomi"],
  ["Raiden Shougun", "Xingqiu", "Xiangling", "Bennett"],
  ["Raiden Shougun", "Sucrose", "Xiangling", "Bennett"],
  ["Raiden Shougun", "Fischl", "Xiangling", "Bennett"],
  ["Raiden Shougun", "Mona", "Xiangling", "Bennett"],

  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Fischl"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Beidou"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Xingqiu"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Sucrose"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Fischl", "Xingqiu"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Fischl", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Fischl", "Sucrose"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Beidou", "Xingqiu"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Beidou", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Beidou", "Sucrose"],
  ["Sangonomiya Kokomi", "Yae Miko", "Fischl", "Xingqiu"],
  ["Sangonomiya Kokomi", "Yae Miko", "Fischl", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Yae Miko", "Fischl", "Sucrose"],
  ["Sangonomiya Kokomi", "Yae Miko", "Beidou", "Xingqiu"],
  ["Sangonomiya Kokomi", "Yae Miko", "Beidou", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Yae Miko", "Beidou", "Sucrose"],
  ["Sangonomiya Kokomi", "Fischl", "Beidou", "Kaedehara Kazuha"],
  ["Sangonomiya Kokomi", "Fischl", "Beidou", "Sucrose"],

  ["Xiao", "Faruzan", "Zhongli", "Bennett"],
  ["Xiao", "Faruzan", "Thoma", "Bennett"],
  ["Xiao", "Faruzan", "Xiangling", "Bennett"],
  ["Xiao", "Faruzan", "Diona", "Bennett"],
  ["Xiao", "Albedo", "Zhongli", "Jean"],
  ["Xiao", "Kaedehara Kazuha", "Zhongli", "Jean"],
  ["Xiao", "Kaedehara Kazuha", "Albedo", "Jean"],
  ["Xiao", "Kaedehara Kazuha", "Zhongli", "Bennett"],
  ["Xiao", "Kaedehara Kazuha", "Albedo", "Bennett"],
  ["Xiao", "Kaedehara Kazuha", "Noelle", "Bennett"],
  ["Xiao", "Venti", "Zhongli", "Jean"],
  ["Xiao", "Venti", "Zhongli", "Bennett"],
  ["Xiao", "Sayu", "Zhongli", "Bennett"],
  ["Xiao", "Raiden Shougun", "Zhongli", "Bennett"],
  ["Xiao", "Sucrose", "Zhongli", "Jean"],
  ["Xiao", "Sucrose", "Zhongli", "Bennett"],
  ["Xiao", "Sucrose", "Noelle", "Jean"],
  ["Xiao", "Sucrose", "Noelle", "Bennett"],

  ["Arataki Itto", "Gorou", "Albedo", "Sangonomiya Kokomi"],
  ["Arataki Itto", "Gorou", "Albedo", "Zhongli"],
  ["Arataki Itto", "Gorou", "Albedo", "Diona"],
  ["Arataki Itto", "Gorou", "Albedo", "Qiqi"],
  ["Arataki Itto", "Gorou", "Albedo", "Bennett"],
  ["Arataki Itto", "Gorou", "Zhongli", "Sangonomiya Kokomi"],
  ["Arataki Itto", "Gorou", "Zhongli", "Diona"],
  ["Arataki Itto", "Gorou", "Zhongli", "Qiqi"],
  ["Arataki Itto", "Gorou", "Zhongli", "Bennett"],
  ["Arataki Itto", "Gorou", "Noelle", "Diona"],
  ["Arataki Itto", "Gorou", "Noelle", "Bennett"],

  ["Aloy", "Xingqiu", "Zhongli", "Sangonomiya Kokomi"],
  ["Aloy", "Xingqiu", "Raiden Shougun", "Zhongli"],
  ["Aloy", "Xiangling", "Xingqiu", "Bennett"],

  ["Yoimiya", "Xingqiu", "Zhongli", "Bennett"],
  ["Yoimiya", "Xingqiu", "Yunjin", "Bennett"],
  ["Yoimiya", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Yoimiya", "Xingqiu", "Venti", "Bennett"],
  ["Yoimiya", "Xingqiu", "Sucrose", "Bennett"],
  ["Yoimiya", "Xingqiu", "Albedo", "Zhongli"],
  ["Yoimiya", "Xingqiu", "Raiden Shougun", "Bennett"],
  ["Yoimiya", "Xingqiu", "Yae Miko", "Bennett"],
  ["Yoimiya", "Xingqiu", "Fischl", "Bennett"],
  ["Yoimiya", "Mona", "Zhongli", "Bennett"],
  ["Yoimiya", "Mona", "Venti", "Bennett"],
  ["Yoimiya", "Mona", "Sucrose", "Bennett"],
  ["Yoimiya", "Mona", "Albedo", "Zhongli"],
  ["Yoimiya", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Yoimiya", "Mona", "Raiden Shougun", "Bennett"],
  ["Yoimiya", "Mona", "Yae Miko", "Bennett"],
  ["Yoimiya", "Mona", "Fischl", "Bennett"],

  ["Eula", "Raiden Shougun", "Zhongli", "Bennett"],
  ["Eula", "Raiden Shougun", "Zhongli", "Diona"],
  ["Eula", "Raiden Shougun", "Albedo", "Diona"],
  ["Eula", "Raiden Shougun", "Noelle", "Diona"],
  ["Eula", "Raiden Shougun", "Fischl", "Diona"],
  ["Eula", "Yae Miko", "Zhongli", "Bennett"],
  ["Eula", "Yae Miko", "Zhongli", "Diona"],
  ["Eula", "Yae Miko", "Albedo", "Diona"],
  ["Eula", "Yae Miko", "Noelle", "Diona"],
  ["Eula", "Yae Miko", "Fischl", "Diona"],
  ["Eula", "Rosaria", "Raiden Shougun", "Sangonomiya Kokomi"],
  ["Eula", "Rosaria", "Yae Miko", "Sangonomiya Kokomi"],
  ["Eula", "Rosaria", "Fischl", "Sangonomiya Kokomi"],
  ["Eula", "Rosaria", "Beidou", "Sangonomiya Kokomi"],
  ["Eula", "Fischl", "Zhongli", "Diona"],
  ["Eula", "Fischl", "Albedo", "Diona"],
  ["Eula", "Fischl", "Noelle", "Diona"],
  ["Eula", "Fischl", "Bennett", "Diona"],

  ["Kamisato Ayaka", "Mona", "Venti", "Diona"],
  ["Kamisato Ayaka", "Mona", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayaka", "Mona", "Sucrose", "Diona"],
  ["Kamisato Ayaka", "Xingqiu", "Venti", "Diona"],
  ["Kamisato Ayaka", "Xingqiu", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayaka", "Xingqiu", "Sucrose", "Diona"],
  ["Kamisato Ayaka", "Shenhe", "Venti", "Bennett"],
  ["Kamisato Ayaka", "Shenhe", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayaka", "Shenhe", "Sucrose", "Bennett"],
  ["Kamisato Ayaka", "Shenhe", "Venti", "Sangonomiya Kokomi"],
  ["Kamisato Ayaka", "Shenhe", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Kamisato Ayaka", "Shenhe", "Sucrose", "Sangonomiya Kokomi"],
  ["Kamisato Ayaka", "Shenhe", "Bennett", "Sangonomiya Kokomi"],
  ["Kamisato Ayaka", "Nahida", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayaka", "Nahida", "Venti", "Bennett"],
  ["Kamisato Ayaka", "Nahida", "Sucrose", "Bennett"],
  ["Kamisato Ayaka", "Nahida", "Xiangling", "Bennett"],

  ["Kamisato Ayato", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Raiden Shougun", "Venti", "Bennett"],
  ["Kamisato Ayato", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Venti", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Venti", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Beidou", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Venti", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Xingqiu", "Venti", "Bennett"],
  ["Kamisato Ayato", "Xingqiu", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Yunjin", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Yunjin", "Kaedehara Kazuha", "Jean"],
  ["Kamisato Ayato", "Yunjin", "Zhongli", "Jean"],
  ["Kamisato Ayato", "Yunjin", "Xingqiu", "Jean"],
  ["Kamisato Ayato", "Yunjin", "Xingqiu", "Bennett"],
  ["Kamisato Ayato", "Beidou", "Yunjin", "Zhongli"],
  ["Kamisato Ayato", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Raiden Shougun", "Venti", "Bennett"],
  ["Kamisato Ayato", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Venti", "Bennett"],
  ["Kamisato Ayato", "Yae Miko", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Venti", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Fischl", "Beidou", "Sangonomiya Kokomi"],
  ["Kamisato Ayato", "Xiangling", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Venti", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Thoma", "Xingqiu"],
  ["Kamisato Ayato", "Ganyu", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayato", "Ganyu", "Venti", "Diona"],
  ["Kamisato Ayato", "Ganyu", "Sucrose", "Diona"],
  ["Kamisato Ayato", "Kamisato Ayaka", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayato", "Kamisato Ayaka", "Venti", "Diona"],
  ["Kamisato Ayato", "Kamisato Ayaka", "Sucrose", "Diona"],
  ["Kamisato Ayato", "Nahida", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Kamisato Ayato", "Nahida", "Zhongli", "Kuki Shinobu"],

  ["Klee", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Klee", "Mona", "Venti", "Bennett"],
  ["Klee", "Mona", "Sucrose", "Bennett"],
  ["Klee", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Klee", "Raiden Shougun", "Venti", "Bennett"],
  ["Klee", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Klee", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Klee", "Xingqiu", "Venti", "Bennett"],
  ["Klee", "Xingqiu", "Sucrose", "Bennett"],
  ["Klee", "Fischl", "Kaedehara Kazuha", "Bennett"],
  ["Klee", "Fischl", "Venti", "Bennett"],
  ["Klee", "Fischl", "Sucrose", "Bennett"],

  ["Tartaglia", "Xiangling", "Kaedehara Kazuha", "Bennett"],
  ["Tartaglia", "Xiangling", "Sucrose", "Bennett"],
  ["Tartaglia", "Xiangling", "Raiden Shougun", "Bennett"],
  ["Tartaglia", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Tartaglia", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Tartaglia", "Ganyu", "Kaedehara Kazuha", "Diona"],
  ["Tartaglia", "Kaeya", "Xingqiu", "Diona"],

  ["Noelle", "Albedo", "Zhongli", "Jean"],
  ["Noelle", "Albedo", "Xingqiu", "Chongyun"],
  ["Noelle", "Zhongli", "Raiden Shougun", "Chongyun"],
  ["Noelle", "Zhongli", "Fischl", "Chongyun"],

  ["Razor", "Rosaria", "Raiden Shougun", "Bennett"],
  ["Razor", "Rosaria", "Fischl", "Bennett"],
  ["Razor", "Rosaria", "Traveler_electro", "Bennett"],
  ["Razor", "Rosaria", "Raiden Shougun", "Barbara"],
  ["Razor", "Rosaria", "Fischl", "Barbara"],
  ["Razor", "Rosaria", "Traveler_electro", "Barbara"],
  ["Razor", "Kaeya", "Raiden Shougun", "Bennett"],
  ["Razor", "Kaeya", "Fischl", "Bennett"],
  ["Razor", "Kaeya", "Traveler_electro", "Bennett"],
  ["Razor", "Kaeya", "Raiden Shougun", "Barbara"],
  ["Razor", "Kaeya", "Fischl", "Barbara"],
  ["Razor", "Kaeya", "Traveler_electro", "Barbara"],
  ["Razor", "Xingqiu", "Raiden Shougun", "Qiqi"],
  ["Razor", "Xingqiu", "Fischl", "Qiqi"],
  ["Razor", "Xingqiu", "Traveler_electro", "Qiqi"],

  ["Lisa", "Xingqiu", "Xiangling", "Bennett"],
  ["Lisa", "Kujou Sara", "Kaedehara Kazuha", "Bennett"],
  ["Lisa", "Kujou Sara", "Venti", "Bennett"],
  ["Lisa", "Kujou Sara", "Sucrose", "Bennett"],
  ["Lisa", "Beidou", "Xiangling", "Albedo"],
  ["Lisa", "Beidou", "Xiangling", "Zhongli"],

  ["Xinyan", "Zhongli", "Albedo", "Bennett"],

  ["Amber", "Mona", "Kaedehara Kazuha", "Bennett"],
  ["Amber", "Mona", "Zhongli", "Bennett"],

  ["Yanfei", "Xingqiu", "Kaedehara Kazuha", "Bennett"],
  ["Yanfei", "Xingqiu", "Venti", "Bennett"],
  ["Yanfei", "Xingqiu", "Sucrose", "Bennett"],
  ["Yanfei", "Xingqiu", "Zhongli", "Bennett"],
  ["Yanfei", "Xingqiu", "Noelle", "Bennett"],
  ["Yanfei", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Yanfei", "Raiden Shougun", "Venti", "Bennett"],
  ["Yanfei", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Yanfei", "Raiden Shougun", "Zhongli", "Bennett"],
  ["Yanfei", "Fischl", "Kaedehara Kazuha", "Bennett"],
  ["Yanfei", "Fischl", "Venti", "Bennett"],
  ["Yanfei", "Fischl", "Sucrose", "Bennett"],

  ["Ningguang", "Zhongli", "Xiangling", "Bennett"],
  ["Ningguang", "Zhongli", "Thoma", "Bennett"],
  ["Ningguang", "Albedo", "Xiangling", "Bennett"],
  ["Ningguang", "Albedo", "Thoma", "Bennett"],
  ["Ningguang", "Noelle", "Xiangling", "Bennett"],
  ["Ningguang", "Noelle", "Thoma", "Bennett"],
  ["Ningguang", "Raiden Shougun", "Thoma", "Bennett"],
  ["Ningguang", "Xingqiu", "Xiangling", "Bennett"],
  ["Ningguang", "Fischl", "Thoma", "Bennett"],

  ["Chongyun", "Diona", "Xiangling", "Bennett"],
  ["Chongyun", "Diona", "Thoma", "Bennett"],
  ["Chongyun", "Kaeya", "Xiangling", "Bennett"],
  ["Chongyun", "Kaeya", "Thoma", "Bennett"],
  ["Chongyun", "Xingqiu", "Xiangling", "Bennett"],

  ["Hutao", "Yelan", "Zhongli", "Albedo"],
  ["Hutao", "Yelan", "Zhongli", "Bennett"],
  ["Hutao", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Hutao", "Yelan", "Sucrose", "Bennett"],
  ["Yoimiya", "Yelan", "Zhongli", "Bennett"],
  ["Yoimiya", "Yelan", "Yunjin", "Bennett"],
  ["Yoimiya", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Yoimiya", "Yelan", "Sucrose", "Bennett"],
  ["Kamisato Ayaka", "Yelan", "Venti", "Diona"],
  ["Kamisato Ayaka", "Yelan", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayaka", "Yelan", "Sucrose", "Diona"],
  ["Keqing", "Yelan", "Raiden Shougun", "Bennett"],
  ["Keqing", "Yelan", "Raiden Shougun", "Jean"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Yae Miko", "Yelan"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Fischl", "Yelan"],
  ["Sangonomiya Kokomi", "Raiden Shougun", "Beidou", "Yelan"],
  ["Sangonomiya Kokomi", "Yae Miko", "Fischl", "Yelan"],
  ["Sangonomiya Kokomi", "Yae Miko", "Beidou", "Yelan"],
  ["Kamisato Ayato", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Kamisato Ayato", "Yelan", "Venti", "Bennett"],
  ["Kamisato Ayato", "Yelan", "Sucrose", "Bennett"],
  ["Kamisato Ayato", "Xiangling", "Thoma", "Yelan"],
  ["Kamisato Ayaka", "Yelan", "Venti", "Diona"],
  ["Kamisato Ayaka", "Yelan", "Kaedehara Kazuha", "Diona"],
  ["Kamisato Ayaka", "Yelan", "Sucrose", "Diona"],
  ["Diluc", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Diluc", "Yelan", "Venti", "Bennett"],
  ["Diluc", "Yelan", "Sucrose", "Bennett"],
  ["Diluc", "Yelan", "Zhongli", "Bennett"],
  ["Diluc", "Yelan", "Raiden Shougun", "Bennett"],
  ["Diluc", "Yelan", "Yae Miko", "Bennett"],
  ["Diluc", "Yelan", "Fischl", "Bennett"],
  ["Klee", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Klee", "Yelan", "Venti", "Bennett"],
  ["Klee", "Yelan", "Sucrose", "Bennett"],
  ["Tartaglia", "Kaeya", "Yelan", "Diona"],
  ["Noelle", "Albedo", "Yelan", "Chongyun"],
  ["Yanfei", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Yanfei", "Yelan", "Venti", "Bennett"],
  ["Yanfei", "Yelan", "Sucrose", "Bennett"],
  ["Yanfei", "Yelan", "Zhongli", "Bennett"],
  ["Yanfei", "Yelan", "Noelle", "Bennett"],
  ["Razor", "Yelan", "Raiden Shougun", "Qiqi"],
  ["Razor", "Yelan", "Fischl", "Qiqi"],
  ["Razor", "Yelan", "Traveler_electro", "Qiqi"],
  ["Ningguang", "Yelan", "Xiangling", "Bennett"],

  ["Tartaglia", "Beidou", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tartaglia", "Beidou", "Sucrose", "Kuki Shinobu"],
  ["Kamisato Ayato", "Beidou", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Kamisato Ayato", "Beidou", "Venti", "Kuki Shinobu"],
  ["Kamisato Ayato", "Beidou", "Sucrose", "Kuki Shinobu"],
  ["Arataki Itto", "Gorou", "Albedo", "Kuki Shinobu"],
  ["Eula", "Shenhe", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Eula", "Shenhe", "Sucrose", "Kuki Shinobu"],
  ["Sucrose", "Xingqiu", "Beidou", "Kuki Shinobu"],
  ["Sucrose", "Yelan", "Beidou", "Kuki Shinobu"],
  ["Klee", "Thoma", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Yanfei", "Thoma", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Yoimiya", "Beidou", "Kaedehara Kazuha", "Kuki Shinobu"],

  ["Shikanoin Heizou", "Xingqiu", "Yae Miko", "Kuki Shinobu"],
  ["Shikanoin Heizou", "Xingqiu", "Beidou", "Kuki Shinobu"],
  ["Shikanoin Heizou", "Xingqiu", "Xiangling", "Thoma"],
  ["Shikanoin Heizou", "Xingqiu", "Xiangling", "Bennett"],
  ["Shikanoin Heizou", "Xingqiu", "Rosaria", "Kaeya"],
  ["Shikanoin Heizou", "Yelan", "Yae Miko", "Kuki Shinobu"],
  ["Shikanoin Heizou", "Yelan", "Beidou", "Kuki Shinobu"],
  ["Shikanoin Heizou", "Yelan", "Xiangling", "Bennett"],
  ["Shikanoin Heizou", "Rosaria", "Xiangling", "Bennett"],
  ["Shikanoin Heizou", "Yelan", "Xingqiu", "Kuki Shinobu"],

  ["Tighnari", "Yae Miko", "Nahida", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Collei", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Traveler_dendro", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Sucrose", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Zhongli", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Nahida", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Collei", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Traveler_dendro", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Sucrose", "Kuki Shinobu"],
  ["Tighnari", "Fischl", "Zhongli", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Nahida", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Collei", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Traveler_dendro", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Sucrose", "Kuki Shinobu"],
  ["Tighnari", "Raiden Shougun", "Zhongli", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Nahida", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Collei", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Traveler_dendro", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Sucrose", "Kuki Shinobu"],
  ["Tighnari", "Keqing", "Zhongli", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Nahida", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Collei", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Traveler_dendro", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Sucrose", "Kuki Shinobu"],
  ["Tighnari", "Lisa", "Zhongli", "Kuki Shinobu"],
  ["Tighnari", "Yae Miko", "Nahida", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Collei", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Sucrose", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Zhongli", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Nahida", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Collei", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Sucrose", "Sangonomiya Kokomi"],
  ["Tighnari", "Fischl", "Zhongli", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Nahida", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Collei", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Sucrose", "Sangonomiya Kokomi"],
  ["Tighnari", "Raiden Shougun", "Zhongli", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Nahida", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Collei", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Sucrose", "Sangonomiya Kokomi"],
  ["Tighnari", "Keqing", "Zhongli", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Nahida", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Collei", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Sucrose", "Sangonomiya Kokomi"],
  ["Tighnari", "Lisa", "Zhongli", "Sangonomiya Kokomi"],
  ["Tighnari", "Yae Miko", "Nahida", "Bennett"],
  ["Tighnari", "Yae Miko", "Collei", "Bennett"],
  ["Tighnari", "Yae Miko", "Traveler_dendro", "Bennett"],
  ["Tighnari", "Yae Miko", "Kaedehara Kazuha", "Bennett"],
  ["Tighnari", "Yae Miko", "Sucrose", "Bennett"],
  ["Tighnari", "Yae Miko", "Zhongli", "Bennett"],
  ["Tighnari", "Fischl", "Nahida", "Bennett"],
  ["Tighnari", "Fischl", "Collei", "Bennett"],
  ["Tighnari", "Fischl", "Traveler_dendro", "Bennett"],
  ["Tighnari", "Fischl", "Kaedehara Kazuha", "Bennett"],
  ["Tighnari", "Fischl", "Sucrose", "Bennett"],
  ["Tighnari", "Fischl", "Zhongli", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Nahida", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Collei", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Traveler_dendro", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Kaedehara Kazuha", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Sucrose", "Bennett"],
  ["Tighnari", "Raiden Shougun", "Zhongli", "Bennett"],
  ["Tighnari", "Keqing", "Nahida", "Bennett"],
  ["Tighnari", "Keqing", "Collei", "Bennett"],
  ["Tighnari", "Keqing", "Traveler_dendro", "Bennett"],
  ["Tighnari", "Keqing", "Kaedehara Kazuha", "Bennett"],
  ["Tighnari", "Keqing", "Sucrose", "Bennett"],
  ["Tighnari", "Keqing", "Zhongli", "Bennett"],
  ["Tighnari", "Lisa", "Nahida", "Bennett"],
  ["Tighnari", "Lisa", "Collei", "Bennett"],
  ["Tighnari", "Lisa", "Traveler_dendro", "Bennett"],
  ["Tighnari", "Lisa", "Kaedehara Kazuha", "Bennett"],
  ["Tighnari", "Lisa", "Sucrose", "Bennett"],
  ["Tighnari", "Lisa", "Zhongli", "Bennett"],

  ["Cyno", "Fischl", "Nahida", "Zhongli"],
  ["Cyno", "Fischl", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Fischl", "Nahida", "Dori"],
  ["Cyno", "Fischl", "Nahida", "Sangonomiya Kokomi"],
  ["Cyno", "Fischl", "Nahida", "Jean"],
  ["Cyno", "Fischl", "Nahida", "Sayu"],
  ["Cyno", "Fischl", "Nahida", "Diona"],
  ["Cyno", "Fischl", "Traveler_dendro", "Zhongli"],
  ["Cyno", "Fischl", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Fischl", "Traveler_dendro", "Dori"],
  ["Cyno", "Fischl", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Cyno", "Fischl", "Traveler_dendro", "Jean"],
  ["Cyno", "Fischl", "Traveler_dendro", "Sayu"],
  ["Cyno", "Fischl", "Traveler_dendro", "Diona"],
  ["Cyno", "Fischl", "Collei", "Zhongli"],
  ["Cyno", "Fischl", "Collei", "Kuki Shinobu"],
  ["Cyno", "Fischl", "Collei", "Dori"],
  ["Cyno", "Fischl", "Collei", "Sangonomiya Kokomi"],
  ["Cyno", "Fischl", "Collei", "Jean"],
  ["Cyno", "Fischl", "Collei", "Sayu"],
  ["Cyno", "Fischl", "Collei", "Diona"],
  ["Cyno", "Beidou", "Nahida", "Zhongli"],
  ["Cyno", "Beidou", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Beidou", "Nahida", "Dori"],
  ["Cyno", "Beidou", "Nahida", "Sangonomiya Kokomi"],
  ["Cyno", "Beidou", "Nahida", "Jean"],
  ["Cyno", "Beidou", "Nahida", "Sayu"],
  ["Cyno", "Beidou", "Nahida", "Diona"],
  ["Cyno", "Beidou", "Traveler_dendro", "Zhongli"],
  ["Cyno", "Beidou", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Beidou", "Traveler_dendro", "Dori"],
  ["Cyno", "Beidou", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Cyno", "Beidou", "Traveler_dendro", "Jean"],
  ["Cyno", "Beidou", "Traveler_dendro", "Sayu"],
  ["Cyno", "Beidou", "Traveler_dendro", "Diona"],
  ["Cyno", "Beidou", "Collei", "Zhongli"],
  ["Cyno", "Beidou", "Collei", "Kuki Shinobu"],
  ["Cyno", "Beidou", "Collei", "Dori"],
  ["Cyno", "Beidou", "Collei", "Sangonomiya Kokomi"],
  ["Cyno", "Beidou", "Collei", "Jean"],
  ["Cyno", "Beidou", "Collei", "Sayu"],
  ["Cyno", "Beidou", "Collei", "Diona"],
  ["Cyno", "Yae Miko", "Nahida", "Zhongli"],
  ["Cyno", "Yae Miko", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Yae Miko", "Nahida", "Dori"],
  ["Cyno", "Yae Miko", "Nahida", "Sangonomiya Kokomi"],
  ["Cyno", "Yae Miko", "Nahida", "Jean"],
  ["Cyno", "Yae Miko", "Nahida", "Sayu"],
  ["Cyno", "Yae Miko", "Nahida", "Diona"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Zhongli"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Dori"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Jean"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Sayu"],
  ["Cyno", "Yae Miko", "Traveler_dendro", "Diona"],
  ["Cyno", "Yae Miko", "Collei", "Zhongli"],
  ["Cyno", "Yae Miko", "Collei", "Kuki Shinobu"],
  ["Cyno", "Yae Miko", "Collei", "Dori"],
  ["Cyno", "Yae Miko", "Collei", "Sangonomiya Kokomi"],
  ["Cyno", "Yae Miko", "Collei", "Jean"],
  ["Cyno", "Yae Miko", "Collei", "Sayu"],
  ["Cyno", "Yae Miko", "Collei", "Diona"],
  ["Cyno", "Lisa", "Nahida", "Zhongli"],
  ["Cyno", "Lisa", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Lisa", "Nahida", "Dori"],
  ["Cyno", "Lisa", "Nahida", "Sangonomiya Kokomi"],
  ["Cyno", "Lisa", "Nahida", "Jean"],
  ["Cyno", "Lisa", "Nahida", "Sayu"],
  ["Cyno", "Lisa", "Nahida", "Diona"],
  ["Cyno", "Lisa", "Traveler_dendro", "Zhongli"],
  ["Cyno", "Lisa", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Lisa", "Traveler_dendro", "Dori"],
  ["Cyno", "Lisa", "Traveler_dendro", "Sangonomiya Kokomi"],
  ["Cyno", "Lisa", "Traveler_dendro", "Jean"],
  ["Cyno", "Lisa", "Traveler_dendro", "Sayu"],
  ["Cyno", "Lisa", "Traveler_dendro", "Diona"],
  ["Cyno", "Lisa", "Collei", "Zhongli"],
  ["Cyno", "Lisa", "Collei", "Kuki Shinobu"],
  ["Cyno", "Lisa", "Collei", "Dori"],
  ["Cyno", "Lisa", "Collei", "Sangonomiya Kokomi"],
  ["Cyno", "Lisa", "Collei", "Jean"],
  ["Cyno", "Lisa", "Collei", "Sayu"],
  ["Cyno", "Lisa", "Collei", "Diona"],
  ["Cyno", "Yelan", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Yelan", "Nahida", "Dori"],
  ["Cyno", "Yelan", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Yelan", "Traveler_dendro", "Dori"],
  ["Cyno", "Yelan", "Collei", "Kuki Shinobu"],
  ["Cyno", "Yelan", "Collei", "Dori"],
  ["Cyno", "Xingqiu", "Nahida", "Kuki Shinobu"],
  ["Cyno", "Xingqiu", "Nahida", "Dori"],
  ["Cyno", "Xingqiu", "Traveler_dendro", "Kuki Shinobu"],
  ["Cyno", "Xingqiu", "Traveler_dendro", "Dori"],
  ["Cyno", "Xingqiu", "Collei", "Kuki Shinobu"],
  ["Cyno", "Xingqiu", "Collei", "Dori"],
  ["Cyno", "Nahida", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Sucrose", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Zhongli", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Albedo", "Kuki Shinobu"],
  ["Cyno", "Traveler_dendro", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Cyno", "Traveler_dendro", "Sucrose", "Kuki Shinobu"],
  ["Cyno", "Traveler_dendro", "Zhongli", "Kuki Shinobu"],
  ["Cyno", "Traveler_dendro", "Albedo", "Kuki Shinobu"],
  ["Cyno", "Collei", "Kaedehara Kazuha", "Kuki Shinobu"],
  ["Cyno", "Collei", "Sucrose", "Kuki Shinobu"],
  ["Cyno", "Collei", "Zhongli", "Kuki Shinobu"],
  ["Cyno", "Collei", "Albedo", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Kaedehara Kazuha", "Dori"],
  ["Cyno", "Nahida", "Sucrose", "Dori"],
  ["Cyno", "Nahida", "Zhongli", "Dori"],
  ["Cyno", "Nahida", "Albedo", "Dori"],
  ["Cyno", "Traveler_dendro", "Kaedehara Kazuha", "Dori"],
  ["Cyno", "Traveler_dendro", "Sucrose", "Dori"],
  ["Cyno", "Traveler_dendro", "Zhongli", "Dori"],
  ["Cyno", "Traveler_dendro", "Albedo", "Dori"],
  ["Cyno", "Collei", "Kaedehara Kazuha", "Dori"],
  ["Cyno", "Collei", "Sucrose", "Dori"],
  ["Cyno", "Collei", "Zhongli", "Dori"],
  ["Cyno", "Collei", "Albedo", "Dori"],

  ["Sangonomiya Kokomi", "Nilou", "Nahida", "Collei"],
  ["Sangonomiya Kokomi", "Nilou", "Traveler_dendro", "Collei"],
  ["Sangonomiya Kokomi", "Nilou", "Nahida", "Traveler_dendro"],
  ["Nahida", "Yelan", "Nilou", "Sangonomiya Kokomi"],
  ["Nahida", "Xingqiu", "Nilou", "Sangonomiya Kokomi"],
  ["Barbara", "Nilou", "Nahida", "Collei"],
  ["Barbara", "Nilou", "Traveler_dendro", "Collei"],
  ["Barbara", "Nilou", "Nahida", "Traveler_dendro"],
  ["Nahida", "Yelan", "Nilou", "Barbara"],
  ["Nahida", "Xingqiu", "Nilou", "Barbara"],
  ["Hutao", "Yelan", "Nilou", "Bennett"],
  ["Diluc", "Yelan", "Nilou", "Bennett"],
  ["Klee", "Yelan", "Nilou", "Bennett"],
  ["Yanfei", "Yelan", "Nilou", "Bennett"],
  ["Hutao", "Xingqiu", "Nilou", "Bennett"],
  ["Diluc", "Xingqiu", "Nilou", "Bennett"],
  ["Klee", "Xingqiu", "Nilou", "Bennett"],
  ["Yanfei", "Xingqiu", "Nilou", "Bennett"],
  ["Nilou", "Xiangling", "Kaedehara Kazuha", "Bennett"],
  ["Nilou", "Xiangling", "Sucrose", "Bennett"],
  ["Nilou", "Thoma", "Kaedehara Kazuha", "Bennett"],
  ["Nilou", "Thoma", "Sucrose", "Bennett"],

  ["Sucrose", "Nahida", "Kuki Shinobu", "Sangonomiya Kokomi"],
  ["Sucrose", "Nahida", "Fischl", "Sangonomiya Kokomi"],
  ["Sucrose", "Nahida", "Yae Miko", "Sangonomiya Kokomi"],
  ["Sucrose", "Nahida", "Beidou", "Sangonomiya Kokomi"],
  ["Sucrose", "Nahida", "Dori", "Sangonomiya Kokomi"],
  ["Sucrose", "Nahida", "Yelan", "Kuki Shinobu"],
  ["Sucrose", "Nahida", "Xingqiu", "Kuki Shinobu"],

  ["Wanderer", "Faruzan", "Kaedehara Kazuha", "Bennett"],
  ["Wanderer", "Faruzan", "Venti", "Bennett"],
  ["Wanderer", "Faruzan", "Jean", "Bennett"],
  ["Wanderer", "Faruzan", "Xiangling", "Bennett"],
  ["Wanderer", "Faruzan", "Thoma", "Bennett"],
  ["Wanderer", "Faruzan", "Yelan", "Bennett"],
  ["Wanderer", "Faruzan", "Xingqiu", "Bennett"],
  ["Wanderer", "Faruzan", "Layla", "Bennett"],
  ["Wanderer", "Faruzan", "Rosaria", "Bennett"],
  ["Wanderer", "Faruzan", "Yunjin", "Bennett"],
  ["Wanderer", "Faruzan", "Yunjin", "Zhongli"],
  ["Wanderer", "Faruzan", "Zhongli", "Bennett"],
  ["Wanderer", "Fischl", "Nahida", "Sangonomiya Kokomi"],
  ["Wanderer", "Yae Miko", "Nahida", "Sangonomiya Kokomi"],
  ["Wanderer", "Yae Miko", "Nahida", "Kuki Shinobu"],
  ["Wanderer", "Beidou", "Nahida", "Sangonomiya Kokomi"],
  ["Wanderer", "Beidou", "Nahida", "Kuki Shinobu"],
];

export { characters, combinations };
